import localFont from "next/font/local";
import "./globals.css";
import mysql from 'mysql2/promise';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const pool = mysql.createPool({
  host: process.env.LIT_STAR_DB_HOST_URL,
  user: process.env.LIT_STAR_DB_USER,
  password: process.env.LIT_STAR_DB_PASSWORD,
  database: process.env.LIT_STAR_DB_NAME,
  waitForConnections: true,
  connectionLimit: 50,
});
export async function MAIN_LIT_STAR_DB(query, params = []) {
  try {
    const [results] = await pool.query(query, params);
    return results;
  } catch (error) {
    throw error;
  }
}
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
